# Generated by Django 4.2.3 on 2023-07-31 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_hospitaluser_is_staff_passwordrecovery'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='role_key',
            field=models.CharField(default=None, max_length=50, null=True, unique=True),
        ),
    ]
