# Generated by Django 4.2.3 on 2023-07-31 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_role_role_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='role_key',
        ),
    ]
