# Generated by Django 4.2.3 on 2023-07-31 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_permission_permission_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitaluser',
            name='hospital_name',
        ),
    ]
