# Generated by Django 4.2.3 on 2023-08-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_hospitaluser_hospital_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaluser',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hospitaluser',
            name='blood_group',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='hospitaluser',
            name='profile_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
