# Generated by Django 4.2.3 on 2023-08-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_hospitaluser_age_hospitaluser_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='descrition',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
