# Generated by Django 4.2.3 on 2023-08-01 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_rename_admin_id_hospital_admin'),
        ('doctors', '0003_remove_doctordetail_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorsToHospital',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('assign_to', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
                ('doctor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.doctordetail')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
